services:
  - type: web
    name: music-library-jan23
    region: frankfurt
    plan: free
    buildCommand: npm install && npm run migrate
    startCommand: node index.js
    env: node
    envVars:
      - key: PGDATABASE
        fromDatabase:
          name: music-library-database-jan22
          property: database
      - key: PGHOST
        fromDatabase:
          name: music-library-database-jan22
          property: host
      - key: PGPASSWORD
        fromDatabase:
          name: music-library-database-jan22
          property: password
      - key: PGUSER
        fromDatabase:
          name: music-library-database-jan22
          property: user
      - key: PGPORT
        fromDatabase:
          name: music-library-database-jan22
          property: port



databases:
  - name: music-library-database-jan22
    plan: free
    region: frankfurt
    databaseName: music_library
    ipAllowList: []

